abstract class CountryConstants{

  static List<Map<String, dynamic>> cities_ru = [
    {"label":"Нур-Султан","value":1},
    {"label":"Алмата","value":2},
    {"label":"Шымкент","value":3},
    {"label":"Актобе","value":4},
    {"label":"Караганда","value":5},
    {"label":"Атырау","value":6},
    {"label":"Тараз","value":7},
    {"label":"Павлодар","value":8},
    {"label":"Семей","value":9},
    {"label":"Усть-Каменогорск","value":10},
    {"label":"Кызылорда","value":11},
    {"label":"Уральск","value":12},
    {"label":"Костанай","value":13},
    {"label":"Петропавловск","value":14},
    {"label":"Актау","value":15},
    {"label":"Темиртау","value":16},
    {"label":"Туркестан","value":17},
    {"label":"Талдыкорган","value":18},
    {"label":"Кокшетау","value":19},
    {"label":"Жанаозен","value":20},
    {"label":"Экибастуз","value":21},
    {"label":"Рудный","value":22},
    {"label": "Северо-Казахстанская область","value":23},
    {"label": "Акмолинская область","value":24},
    {"label": "Актюбинская область","value":25},
    {"label": "Алматинская область","value":26},
    {"label": "Атырауская область","value":27},
    {"label": "Восточно-Казахстанская область","value":28},
    {"label": "Жамбылская область","value":29},
    {"label": "Западно-Казахстанская область","value":30},
    {"label": "Карагандинская область","value":31},
    {"label": "Костанайская область","value":32},
    {"label": "Кызылординская область","value":33},
    {"label": "Мангистауская область","value":34},
    {"label": "Павлодарская область","value":35},
    {"label": "Туркестанская область","value":36},
  ];


  static List<Map<String, dynamic>> cities_en = [
    {"label":"Nur-Sultan","value":1},
    {"label":"Almaty","value":2},
    {"label":"Shymkent","value":3},
    {"label":"Aktobe","value":4},
    {"label":"Karaganda","value":5},
    {"label":"Atyrau","value":6},
    {"label":"Taraz","value":7},
    {"label":"Pavlodar","value":8},
    {"label":"Family","value":9},
    {"label":"Ust-Kamenogorsk","value":10},
    {"label":"Kyzylorda","value":11},
    {"label":"Uralsk","value":12},
    {"label":"Kostanay","value":13},
    {"label":"Petropavlovsk","value":14},
    {"label":"Aktau","value":15},
    {"label":"Temirtau","value":16},
    {"label":"Turkestan","value":17},
    {"label":"Taldykorgan","value":18},
    {"label":"Kokshetau","value":19},
    {"label":"Zhanaozen","value":20},
    {"label":"Ekibastuz","value":21},
    {"label":"Ore","value":22},
    {"label": "North Kazakhstan region","value":23},
    {"label": "Akmola region","value":24},
    {"label": "Aktobe region","value":25},
    {"label": "Almaty region","value":26},
    {"label": "Atyrau region","value":27},
    {"label": "East Kazakhstan region","value":28},
    {"label": "Zhambyl region","value":29},
    {"label": "West Kazakhstan region","value":30},
    {"label": "Karaganda region","value":31},
    {"label": "Kostanay region","value":32},
    {"label": "Kyzylorda region","value":33},
    {"label": "Mangystau region","value":34},
    {"label": "Pavlodar region","value":35},
    {"label": "Turkestan region","value":36},
  ];


  static Map<int,String> citiesMapRu = {
    1:"Нур-Султан",
    2:"Алмата",
    3:"Шымкент",
    4:"Актобе",
    5:"Караганда",
    6:"Атырау",
    7:"Тараз",
    8:"Павлодар",
    9:"Семей",
    10:"Усть-Каменогорск",
    11:"Кызылорда",
    12:"Уральск",
    13:"Костанай",
    14:"Петропавловск",
    15:"Актау",
    16:"Темиртау",
    17:"Туркестан",
    18:"Талдыкорган",
    19:"Кокшетау",
    20:"Жанаозен",
    21:"Экибастуз",
    22:"Рудный",
    23: "Северо-Казахстанская область",
    24: "Акмолинская область",
    25: "Актюбинская область",
    26: "Алматинская область",
    27: "Атырауская область",
    28: "Восточно-Казахстанская область",
    29: "Жамбылская область",
    30: "Западно-Казахстанская область",
    31: "Карагандинская область",
    32:"Костанайская область",
    33:"Кызылординская область",
    34: "Мангистауская область",
    35: "Павлодарская область",
    36: "Туркестанская область",

  };

  static Map<int,String> citiesMapEn = {
    1: "Nursultan",
    2: "Almaty",
    3:"Shymkent",
    4:"Aktobe",
    5:"Karaganda",
    6:"Atyrau",
    7: "Taraz",
    8:"Pavlodar",
    9: "Families",
    10:"Ust-Kamenogorsk",
    11:"Kyzylorda",
    12: "Uralsk",
    13:"Kostanay",
    14:"Petropavlovsk",
    15:"Aktau",
    16:"Temirtau",
    17: "Turkestan",
    18:"Taldykorgan",
    19:"Kokshetau",
    20:"Zhanaozen",
    21:"Ekibastuz",
    22:"Rudny",
    23: "North Kazakhstan region",
    24: "Akmola region",
    25: "Aktobe region",
    26: "Almaty region",
    27: "Atyrau",
    28: "the East Kazakhstan region",
    29: "Zhambyl",
    30: "the West Kazakhstan region",
    31: "Karaganda region",
    32:"Kostanayskaya oblast",
    33:"Kyzylorda region",
    34: "Mangystau",
    35: "Pavlodar region",
    36: "the Turkestan region",

  };


}