name: findout
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 1.11.0
  firebase_auth: 3.3.5
  cloud_firestore: 3.1.6
  firebase_storage: 10.2.5
  image_picker: 0.8.4+4
  font_awesome_flutter: 9.2.0
  connectivity: 3.0.6
  http: ^0.13.4
  paginate_firestore: 1.0.3
  select_form_field: 2.2.0
  datetime_picker_formfield: 2.0.0
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/fonts/
    - assets/sounds/
    - assets/svg/
  uses-material-design: true

