name: findout
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 1.11.0
  firebase_auth: 3.3.5
  cloud_firestore: 3.1.6
  firebase_storage: 10.2.5
  image_picker: 0.8.4+4
  font_awesome_flutter: 9.2.0
  connectivity: 3.0.6
  http: ^0.13.4
  paginate_firestore: 1.0.3
  select_form_field: 2.2.0
  datetime_picker_formfield: 2.0.0
  intl: 0.17.0
  shared_preferences: 2.0.12
  flutterfire_ui: ^0.3.1
  cached_network_image: ^3.2.0
  emoji_picker_flutter: ^1.1.0
  mask_text_input_formatter: ^2.1.0
  ntp: ^2.0.0
  flutter_typeahead: 3.2.4

  flutter: 
    sdk: flutter
  flutter_local_notifications: ^9.3.1
  firebase_messaging: ^11.2.6
  firebase_analytics: ^9.1.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/fonts/
    - assets/sounds/
    - assets/svg/
  uses-material-design: true


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"